---
abstract: 'Author test that validates a package MANIFEST'
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DistManifest
requires:
  Carp: 0
  Cwd: 0
  File::Find: 0
  File::Spec: 0
  File::Spec::Unix: 0
  Module::Manifest: 0
  Test::Builder: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-DistManifest
  homepage: http://search.cpan.org/dist/Test-DistManifest
  repository: git://github.com/jawnsy/Test-DistManifest.git
version: 1.010
